### ISSUE TITLE
run tests from project root

### ISSUE THREAD

**Issue by guyvdbroeck** [wookay/Jive.jl#15]
I would like to be able to run tests from the project root, as `julia --color=yes test/run.jl` while also supporting filtering through ARGS as `julia --color=yes test/run.jl test/IO/`.
My current attempt does not seem to be working:
`runtests("./test/", 
         skip=["run.jl"],
         targets=map(x -> replace(x, "test/" => "", count=1), ARGS))
`

Basically `test/` is being added twice to the path of the files, even if running without filters: could not open file .../test/test/Data/...

**Comment by wookay** [comment]
* test/run.jl
```julia
using Jive
runtests(@__DIR__, skip=["run.jl"])
```

```
$ julia test/run.jl IO
1/1 IO/blah.jl
    Pass 1  (0.10 seconds)
✅  All 1 test has been completed.  (0.45 seconds)
```

sample project:
https://github.com/wookay/TestJiveIssue15.jl

**Comment by guyvdbroeck** [comment]
Thanks. This does the job: `runtests(@__DIR__, skip=["run.jl"], targets=map(x -> replace(x, "test/" => "", count=1), ARGS))`
It runs from the project root while also allowing for filtering through ARGS and autocomplete on the console for the filter directory or file. E.g., I can run `julia --color=yes -pauto test/run.jl test/IO`.
The library is great btw, exactly what I was looking for!
