### ISSUE TITLE
Watch folders silently exits

### ISSUE THREAD

**Issue by taqtiqa-mark** [wookay/Jive.jl#2]
Hi, Thanks you for taking the time to make Jive available.
When I try to have Jive watch the package source files I find the julia/jive process sorrectly identifies the folders holding the source code, yet it immediately silently exits as follows:
```
~/src/Moments.jl/test$ julia --project=.. --color=yes revise.jl Moments
┌ Info: Some variables
└   EmpiricalMomentModel = Moments.EmpiricalMomentModel
watching folders ...
  - ../src
  - ../src/univariate
```

The contents of `revise.jl` are as follows:
```
using Test
using Revise, Jive
using Moments

watch(@__DIR__, sources=[pathof(Moments)]) do path
    @info :changed path
    revise()
    runtests(@__DIR__, skip=["revise.jl"])
end
```

The contents of `runtests.jl` is:
```
using Moments

using Jive
using Test
using Base.CoreLogging

import Test: collect_test_logs, TestLogger

import Base.CoreLogging: BelowMinLevel, Debug, Info, Warn, Error,
       handle_message, shouldlog, min_enabled_level, catch_exceptions

using Printf

runtests(@__DIR__, skip=["revise.jl"])
```

Appreciate any hints or tips about what I have done incorrectly.

**Comment by wookay** [comment]
could I get the `Moments.jl` in github? is is private repo?

**Comment by wookay** [comment]
ah.. you need the Interactive mode or let it wait your task.
`julia -i --color=yes --project=.. revise.jl`

or put this in the end of your `revise.jl`
`Base.JLOptions().isinteractive==0 && wait()`

**Comment by taqtiqa-mark** [comment]
Thanks that was it.  I went with the second option, only because it is more expressive when you read it that the `-i` command line option.
