### ISSUE TITLE
Some tests getting ignored in new release v0.2.8

### ISSUE THREAD

**Issue by khosravipasha** [wookay/Jive.jl#26]
Recently we got a drop in our codecoverage without changining much on our side, after investigating it seems the cause is the new version of Jive (0.2.8). Now the tests that are directly in the `./test` folder are not being run. I confirmed this locally and using v0.2.7 runs all our tests but 0.2.8 does not.

Is this expected behaviour?  Here's were we run all tests [run_tests.jl](https://github.com/Juice-jl/LogicCircuits.jl/blob/master/test/runtests.jl).

More info:
- Here's one build that ignores those tests v0.2.8 [travis link](https://travis-ci.org/github/Juice-jl/LogicCircuits.jl/jobs/716038997)
- Here's one build that runs all tests v0.2.7 [travis link](https://travis-ci.org/github/Juice-jl/LogicCircuits.jl/jobs/714423959)

This is not a big issue since moving our tests inside a folder fixes the issue, but wanted to make sure if this is expected or not.

**Comment by wookay** [comment]
thanks for the issue. fixed on PR #27.
