### ISSUE TITLE
include fails in v0.2.19

### ISSUE THREAD

**Issue by dpinol** [wookay/Jive.jl#46]
Calling `include("...")` from tests now fails. I'll propose a PR

**Comment by dpinol** [comment]
Hi,
that's as far as I got https://github.com/wookay/Jive.jl/pull/47
do you know how to fix my PR?

**Comment by wookay** [comment]
thanks for the issue.
I'll release  v0.2.20 soon with 0b135154fc58cec6eb03b9aaec260fa11d949961.

and this post may help you.
How to update your PR on GitHub
https://ffeathers.wordpress.com/2020/01/12/how-to-update-your-pr-on-github/
