### ISSUE TITLE
@__REPL__ does not show relevant context when using runtests with context=nothing

### ISSUE THREAD

**Issue by nrontsis** [wookay/Jive.jl#60]
Using `@__REPL__` in a test suite that uses `Jive's` `runtest` results in a REPL that has no access to the local scope/variables at the place where `@__REPL__` was called from.

Using `context=Main` appears to solves this, but then part of old test code might persist across runs (e.g. deleted function definitions in test files).

Off topic: I think that using [private contexts for every test file](https://github.com/wookay/Jive.jl/pull/47/files#diff-8d1972610177a7d52fe69a3ab7fd21f146afa0a53f88430dd5960368cd75a6f2R497) has other side effects like not being able to  multiple dispatch on a custom test type (defined in the test files). I can try to produce minimal example for these.

**Comment by nrontsis** [comment]
Actually, even when specifying the context to be Main, @__REPL__ is not useful when used in testset.

I found that Infiltrator.jl works fine as an alternative. Perhaps it’s worth deprecating this package’s @__REPL__ for Infiltrator.jl?

**Comment by wookay** [comment]
Thanks for the feedback.
Although `@__REPL__` macro is just useful for only to track the global variable,
I don't like that to be deprecated now.

well, Infiltrator.jl provides such a good way to track the local scopes on the REPL.
but when you want to things to debug,
that's the time to use the debugger and you would to use tools like VS Code.

**Comment by nrontsis** [comment]
Ok, thanks, closing given [087f205](https://github.com/wookay/Jive.jl/commit/087f2054b5aca8d00082706c9b5dc0f2fe31b763).

> but when you want to things to debug,
that's the time to use the debugger and you would to use tools like VS Code.

I had [some issues last time I tried VSCode to debug `testset`s](https://discourse.julialang.org/t/how-to-debug-exception-triggered-by-unit-test-in-vscode/90438). I am curious to hear about your workflow on debugging tests. Thanks!

**Comment by nrontsis** [comment]
>> but when you want to things to debug,
that's the time to use the debugger and you would to use tools like VS Code.

> I had [some issues last time I tried VSCode to debug testsets](https://discourse.julialang.org/t/how-to-debug-exception-triggered-by-unit-test-in-vscode/90438). I am curious to hear about your workflow on debugging tests. Thanks!

According to [this](https://github.com/JuliaDebug/Debugger.jl/issues/231) the debugger does not work inside macros, and thus in test sets?
